ARG RUBY_VERSION
FROM ruby:$RUBY_VERSION

ENV LANG C.UTF-8

ENV BASE_PACKAGES="alpine-sdk build-base tzdata" \
    FAVORITE_PACKAGE="less"
RUN apk update && \
    apk upgrade && \
    apk --update --no-cache add \
        ${BASE_PACKAGES} \
        ${FAVORITE_PACKAGE}

ARG GEM_NAME
WORKDIR /$GEM_NAME

ARG BUNDLER_VERSION
ARG RAILS_VERSION
RUN gem update --system && \
    gem install bundler:$BUNDLER_VERSION && \
    gem install rails:$RAILS_VERSION

# https://github.com/bundler/bundler/issues/6154
ENV BUNDLE_GEMFILE='/app/Gemfile'
