version: '3'
services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/usr/local/bundle
  app:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile.dev
      args:
        GEM_NAME: "${GEM_NAME}"
        BUNDLER_VERSION: "${BUNDLER_VERSION}"
        RUBY_VERSION: "${RUBY_VERSION}"
    env_file:
      - .env
    volumes:
      - bundle_install:/usr/local/bundle
      - "./:/${GEM_NAME}"
    stdin_open: true
    tty: true
volumes:
  bundle_install:
